version: '3'

services:
  web:
    build: .
    environment:
      - APP_AUTH_TOKEN=8STR7A1UL0FQYW18
    ports:
      - "9292:9292"
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  test:
    build: .
    environment:
      - APP_AUTH_TOKEN=8STR7A1UL0FQYW18
    volumes:
      - .:/usr/src/app
    command: bundle exec rspec

volumes:
  redis-data:
